import os
from pathlib import Path

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

SRCS = Glob('src/*.c*')
SRCS += Glob('ui/settings_page*.cpp')
SRCS += Glob('ui/settings_rtc_api.cpp')
SRCS += Glob('ui/settings_audio_api.cpp')
SRCS += Glob('ui/settings_adb_api.cpp')
SRCS += Glob('ui/settings_adb_state.cpp')
SRCS += Glob('ui/settings_wifi_api.cpp')
SRCS += Glob('ui/settings_system*.cpp')
SRCS += Glob('ui/settings_t12b_*.cpp')
SRCS += Glob('ui/model/setup_value_policy.cpp')
INCLUDE = [ADir('.'), ADir('include'), ADir('ui')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['cp0_lvgl', 'lvgl_component', 'pthread', 'Sigslot', 'eventpp']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = [] #'-std=c++20'
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

app_launch_static_root = Path(env['PROJECT_PATH']) / 'APPLaunch'
if app_launch_static_root.is_dir():
    STATIC_FILES.append((str(app_launch_static_root), 'APPLaunch'))


SRCS += append_srcs_dir(ADir('assets'))

project_target = 'ui_test'
env['PROJECT_NAME'] = project_target

lvgl_component = list(filter(lambda x: x['target'] == 'lvgl_component', env['COMPONENTS']))[0]
toolchain_sysroot = os.environ.get('CONFIG_TOOLCHAIN_SYSROOT', '') or '/'

if 'CONFIG_V9_5_LV_USE_SDL' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['SDL2']
    lvgl_component['INCLUDE'] += ['/usr/include/SDL2']
    lvgl_component['DEFINITIONS'] += ['-D_REENTRANT']

if 'CONFIG_V9_5_LV_USE_FREETYPE' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['freetype']
    lvgl_component['INCLUDE'] += [
        f"{os.path.join(toolchain_sysroot, 'usr','include', 'freetype2')}",
        f"{os.path.join(toolchain_sysroot, 'usr','include', 'libpng16')}"
        ]


for src in lvgl_component['SRCS']:
    if 'lv_sdl_keyboard.c' in str(src):
        lvgl_component['SRCS'].remove(src)

# REQUIREMENTS += ['Backward_cpp']


env['COMPONENTS'].append({'target':project_target,
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'STATIC_FILES':STATIC_FILES,
                          'REGISTER':'project'
                          })
